---
abstract: 'Use L<Dist::Zilla> like AVAR does'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-AVAR
no_index: {}
requires:
  Dist::Zilla: 1.092990
  Dist::Zilla::Plugin::Authority: 0
  Dist::Zilla::Plugin::CompileTests: 0
  Dist::Zilla::Plugin::MakeMaker::Awesome: 0
  Dist::Zilla::Plugin::MetaNoIndex: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0.06
  Dist::Zilla::Plugin::VersionFromPrev: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle: 0
  Moose: 0
  Moose::Autobox: 0
  perl: 5.10.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-AVAR
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-AVAR/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/avar/dist-zilla-pluginbundle-avar.git
version: 0.20
x_authority: cpan:AVAR
